name: Build ya-webadb

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ya-webadb
        uses: actions/checkout@v4
        with:
          repository: yume-chan/ya-webadb

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm -r run build

      - name: Find and upload dist folders
        run: |
          DIST_DIRS=$(find . -type d -name dist | tr '\n' ' ')
          if [ -z "$DIST_DIRS" ]; then
            echo "No dist directories found"
            exit 1
          fi
          echo "Found dist directories: $DIST_DIRS"
        id: dist_paths

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ya-webadb-dist-${{ github.sha }}
          path: ${{ steps.dist_paths.outputs.paths }}
          if-no-files-found: error
          
