name: OpenWrt CLI Boot MSM8916

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-arm-linux-gnueabi \
            libncurses-dev bc git cpio gzip wget mkbootimg curl \
            libssl-dev flex bison libelf-dev u-boot-tools \
            device-tree-compiler qemu-system-arm


      - name: Download OpenWrt rootfs (CLI)
        run: |
          mkdir -p out/rootfs
          wget https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/targets/armvirt/64/immortalwrt-18.06-k5.4-snapshot-r12302-b2370aa432-armvirt-64-rootfs-ext4.img.gz -O rootfs.img.gz
          gunzip rootfs.img.gz
          mv rootfs.img out/rootfs/rootfs.img

      - name: Create initramfs (mount eMMC rootfs)
        run: |
          mkdir -p initramfs/{dev,proc,sys,mnt}
          cat << 'EOF' > initramfs/init
          #!/bin/sh
          mount -t devtmpfs devtmpfs /dev
          mount -t proc proc /proc
          mount -t sysfs sysfs /sys

          echo "[+] Initramfs: mounting rootfs from /dev/mmcblk0p26"
          mount /dev/mmcblk0p26 /mnt || {
            echo "[!] Failed to mount rootfs"
            exec sh
          }

          exec switch_root /mnt /sbin/init
          EOF

          chmod +x initramfs/init
          (cd initramfs && find . | cpio -o -H newc | gzip) > out/initramfs.cpio.gz

      - name: Create boot.img
        run: |
          mkbootimg --kernel out/Image.gz-dtb \
            --ramdisk out/initramfs.cpio.gz \
            --pagesize 2048 \
            --base 0x80000000 \
            --cmdline 'console=ttyMSM0,115200 init=/init rootfstype=ext4 root=/dev/ram0' \
            --output out/boot.img

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-msm8916-cli-boot
          path: out/
          
