name: OpenWrt CLI Boot MSM8916

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev bc git \
            cpio gzip wget mkbootimg curl libssl-dev flex bison \
            libelf-dev u-boot-tools device-tree-compiler qemu-system-arm

      - name: Clone msm8916 kernel (6.12.1)
        run: |
          git clone -b msm8916/6.12.1 https://github.com/msm8916-mainline/linux.git kernel-msm8916

      - name: Build kernel zImage + dtb
        run: |
          cd kernel-msm8916
          make ARCH=arm multi_v7_defconfig
          make -j$(nproc) ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- zImage dtbs
          mkdir -p ../out/kernel
          cp arch/arm/boot/zImage ../out/kernel/zImage
          find arch/arm/boot/dts -name "*msm8916*.dtb" -exec cat {} + > ../out/kernel/msm8916.dtb
          cat ../out/kernel/zImage ../out/kernel/msm8916.dtb > ../out/Image.gz-dtb

      - name: Download OpenWrt rootfs (ext4 CLI)
        run: |
          mkdir -p out/rootfs
          wget https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/targets/armvirt/32/immortalwrt-18.06-k5.4-snapshot-r12302-b2370aa432-armvirt-32-rootfs-ext4.img.gz -O rootfs.img.gz
          gunzip rootfs.img.gz
          mv rootfs.img out/rootfs/rootfs.img

      - name: Create initramfs (switch_root to rootfs)
        run: |
          mkdir -p initramfs/{dev,proc,sys,mnt}
          cat << 'EOF' > initramfs/init
          #!/bin/sh
          mount -t devtmpfs devtmpfs /dev
          mount -t proc proc /proc
          mount -t sysfs sysfs /sys

          echo "[+] Initramfs: mounting rootfs..."
          mount /dev/mmcblk0p26 /mnt || {
            echo "[!] Failed to mount rootfs"
            exec sh
          }

          exec switch_root /mnt /sbin/init
          EOF

          chmod +x initramfs/init
          (cd initramfs && find . | cpio -o -H newc | gzip) > out/initramfs.cpio.gz

      - name: Create boot.img
        run: |
          mkbootimg --kernel out/Image.gz-dtb \
            --ramdisk out/initramfs.cpio.gz \
            --pagesize 2048 \
            --base 0x80000000 \
            --cmdline 'console=ttyMSM0,115200 init=/init rootfstype=ext4 root=/dev/ram0' \
            --output out/boot.img

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-msm8916-cli-boot
          path: out/
          
