name: Build OpenWrt + Kernel MSM8916 for Redmi 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev bc git \
            cpio gzip wget mkbootimg curl libssl-dev flex bison \
            libelf-dev u-boot-tools device-tree-compiler

      - name: Clone kernel MSM8916-mainline
        run: |
          git clone --depth=1 https://github.com/msm8916-mainline/linux.git kernel-msm8916

      - name: Build kernel zImage + dtb
        run: |
          cd kernel-msm8916
          make ARCH=arm msm8916_defconfig
          make -j$(nproc) ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- zImage dtbs
          mkdir -p ../out/kernel
          cp arch/arm/boot/zImage ../out/kernel/zImage
          cp arch/arm/boot/dts/qcom/msm8916-wingtech-wt88047.dtb ../out/kernel/msm8916.dtb
          cat ../out/kernel/zImage ../out/kernel/msm8916.dtb > ../out/Image.gz-dtb

      - name: Fetch OpenWrt rootfs armv7 + LuCI
        run: |
          mkdir -p out/rootfs
          wget https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/targets/armvirt/32/immortalwrt-18.06-k5.4-snapshot-r12302-b2370aa432-armvirt-32-rootfs-ext4.img.gz -O rootfs.img.gz
          gunzip rootfs.img.gz
          mv rootfs.img out/rootfs/rootfs.img

      - name: Create initramfs
        run: |
          mkdir -p initramfs/{dev,proc,sys,mnt/root}
          echo '#!/bin/sh' > initramfs/init
          echo 'mount -t devtmpfs devtmpfs /dev' >> initramfs/init
          echo 'mount -t proc proc /proc' >> initramfs/init
          echo 'mount -t sysfs sysfs /sys' >> initramfs/init
          echo 'echo "[initramfs] Mounting OpenWrt rootfs..."' >> initramfs/init
          echo 'mount /dev/mmcblk1p1 /mnt/root' >> initramfs/init
          echo 'exec switch_root /mnt/root /sbin/init' >> initramfs/init
          chmod +x initramfs/init
          (cd initramfs && find . | cpio -o -H newc | gzip) > out/initramfs.cpio.gz

      - name: Build boot.img
        run: |
          mkbootimg --kernel out/Image.gz-dtb \
            --ramdisk out/initramfs.cpio.gz \
            --pagesize 2048 \
            --base 0x80000000 \
            --cmdline 'console=ttyMSM0,115200n8 androidboot.selinux=permissive rootfstype=ext4 root=/dev/ram0' \
            --output out/boot.img

      - name: Upload boot pack
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-msm8916-redmi2-pack
          path: out/
          
