name: Build OpenWrt Boot Image for MSM8916 (ARM64)

on:
  workflow_dispatch:

jobs:
  build-bootimg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bc \
          bison \
          flex \
          git \
          curl \
          lz4 \
          cpio \
          mkbootimg \
          gcc-aarch64-linux-gnu \
          libssl-dev \
          libelf-dev \
          python3-pip \
          wget \
          rsync \
          unzip \
          device-tree-compiler

    - name: Clone MSM8916 Kernel (msm8916/6.12.1)
      run: |
        git clone --depth=1 -b msm8916/6.12.1 https://github.com/msm8916-mainline/linux.git kernel-msm8916

    - name: Build Kernel and DTB
      run: |
        cd kernel-msm8916
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- msm8916_defconfig
        make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image.gz dtbs
        cp arch/arm64/boot/Image.gz ../Image.gz
        find arch/arm64/boot/dts -name "msm8916-*.dtb" -exec cat {} + > ../msm8916.dtb

    - name: Combine Kernel and DTB
      run: |
        cat Image.gz msm8916.dtb > Image.gz-dtb

    - name: Download OpenWrt Rootfs (Initramfs)
      run: |
        curl -L -o rootfs.cpio.gz https://downloads.openwrt.org/releases/23.05.0/targets/ipq40xx/generic/openwrt-23.05.0-ipq40xx-generic-rootfs.cpio.gz

    - name: Build boot-openwrt.img
      run: |
        mkbootimg \
          --kernel Image.gz-dtb \
          --ramdisk rootfs.cpio.gz \
          --cmdline "console=tty0 console=ttyMSM0,115200 root=/dev/ram0 rootfstype=ext4 rw init=/bin/procd" \
          --base 0x80078000 \
          --pagesize 2048 \
          --kernel_offset 0x00008000 \
          --ramdisk_offset 0x7ff88000 \
          --second_offset 0x7ff88000 \
          --tags_offset 0x01d88000 \
          --header_version 0 \
          --hash sha1 \
          -o boot-openwrt.img

    - name: Upload boot.img
      uses: actions/upload-artifact@v4
      with:
        name: boot-openwrt-msm8916
        path: boot-openwrt.img
        
