name: Build bootable image Redmi 2 (postmarketOS kernel + ImmortalWRT rootfs)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip android-sdk-tools binfmt-support e2fsprogs \
                              squashfs-tools git build-essential qemu-user-static mkbootimg 

      - name: Download postmarketOS image
        run: |
          wget https://images.postmarketos.org/bpo/v25.06/xiaomi-wt88047/sxmo-de-sway/20250621-1801/20250621-1801-postmarketOS-v25.06-sxmo-de-sway-1.17.1-xiaomi-wt88047.img.xz
          unxz 20250621-1801-postmarketOS-v25.06-sxmo-de-sway-1.17.1-xiaomi-wt88047.img.xz
          mv 20250621-1801-postmarketOS-v25.06-sxmo-de-sway-1.17.1-xiaomi-wt88047.img postmarketos.img

      - name: Extract kernel and dtb from postmarketOS boot.img
        run: |
          # Pastikan punya tool unpackbootimg dari android-sdk-tools
          # Kalau boot.img belum punya, sesuaikan path
          wget https://images.postmarketos.org/bpo/v25.06/xiaomi-wt88047/boot.img
          mkdir boot_extract
          unpackbootimg -i boot.img -o boot_extract
          # hasil: zImage, dtb.img di boot_extract/

      - name: Download ImmortalWRT rootfs
        run: |
          wget https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/targets/armvirt/64/openwrt-armvirt-64-root.ext4.gz
          gunzip openwrt-armvirt-64-root.ext4.gz
          mv openwrt-armvirt-64-root.ext4 immortal-rootfs.img

      - name: Mount and customize ImmortalWRT rootfs
        run: |
          sudo mkdir wrtfs
          sudo mount -o loop immortal-rootfs.img wrtfs
          sudo mount --bind /dev wrtfs/dev
          sudo mount --bind /proc wrtfs/proc
          sudo mount --bind /sys wrtfs/sys

          sudo chroot wrtfs /bin/sh -c "opkg update && opkg install luci"

          sudo umount wrtfs/dev
          sudo umount wrtfs/proc
          sudo umount wrtfs/sys
          sudo umount wrtfs
          sudo rmdir wrtfs

          sudo e2fsck -fy immortal-rootfs.img
          sudo resize2fs -M immortal-rootfs.img

      - name: Create new boot.img combining kernel + dtb + rootfs
        run: |
          # gunakan mkbootimg tool untuk gabungkan kernel+dtb+ramdisk
          # contoh:
          mkbootimg --kernel boot_extract/zImage --ramdisk boot_extract/ramdisk.img \
                    --cmdline "console=ttyMSM0,115200,n8 androidboot.hardware=qcom" \
                    --base 0x10000000 --pagesize 4096 --output new-boot.img
          # jika perlu, buat userdata.img dari immortal-rootfs.img atau sparse.img sesuai kebutuhan

      - name: Upload built images
        uses: actions/upload-artifact@v4
        with:
          name: redmi2-built-images
          path: |
            new-boot.img
            immortal-rootfs.img
