name: Build KernelSU for J320G

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3

      - name: Set up Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabi bc libncurses-dev flex bison
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 --depth=1 toolchain

      - name: Clone KernelSU
        run: |
          git clone --depth=1 https://github.com/tiann/KernelSU ksu
          cp -r ksu/* ./  # atau masukkan ke lokasi sesuai struktur kernel

      - name: Configure Kernel
        run: |
          export ARCH=arm
          export CROSS_COMPILE=${{ github.workspace }}/toolchain/bin/arm-linux-androideabi-
          make j3lte_defconfig

      - name: Compile Kernel
        run: |
          export ARCH=arm
          export CROSS_COMPILE=${{ github.workspace }}/toolchain/bin/arm-linux-androideabi-
          make -j$(nproc)

      - name: Repack boot.img
        run: |
          git clone https://github.com/osm0sis/mkbootimg.git
          # Misalnya kamu sudah punya base boot.img → extract dulu
          # Ganti zImage hasil compile → pack ulang
          mkdir boot
          cp arch/arm/boot/zImage boot/
          # Lanjutkan packing ulang jadi boot.img

      - name: Upload boot.img
        uses: actions/upload-artifact@v3
        with:
          name: boot-img
          path: boot/boot.img
          
