name: Build ImmortalWRT RootFS + Custom Boot.img for Redmi 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget xz-utils android-bootimg-tools e2fsprogs \
                            qemu-user-static binfmt-support unzip build-essential \
                            android-sdk-platform-tools simg2img img2simg

    - name: Download postmarketOS boot.img
      run: |
        wget https://images.postmarketos.org/bpo/v25.06/xiaomi-wt88047/boot.img
        mkdir boot_extract
        unpackbootimg -i boot.img -o boot_extract

    - name: Download ImmortalWRT rootfs (ext4)
      run: |
        wget https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/targets/armvirt/64/immortalwrt-18.06-k5.4-snapshot-r12302-b2370aa432-armvirt-64-rootfs-ext4.img.gz
        gunzip immortalwrt-18.06-k5.4-snapshot-r12302-b2370aa432-armvirt-64-rootfs-ext4.img.gz
        mv immortalwrt-18.06-k5.4-snapshot-*.img immortal-rootfs.img

    - name: Mount and customize rootfs
      run: |
        sudo mkdir wrtfs
        sudo mount -o loop immortal-rootfs.img wrtfs
        sudo mount --bind /dev wrtfs/dev
        sudo mount --bind /proc wrtfs/proc
        sudo mount --bind /sys wrtfs/sys

        sudo chroot wrtfs /bin/sh -c "opkg update && opkg install luci"

        sudo umount wrtfs/dev
        sudo umount wrtfs/proc
        sudo umount wrtfs/sys
        sudo umount wrtfs
        sudo rmdir wrtfs

        sudo e2fsck -fy immortal-rootfs.img
        sudo resize2fs -M immortal-rootfs.img

    - name: Convert rootfs to sparse image
      run: |
        img2simg immortal-rootfs.img immortal-rootfs.sparse.img

    - name: Create new boot.img with updated cmdline
      run: |
        mkbootimg \
          --kernel boot_extract/boot.img-zImage \
          --ramdisk boot_extract/boot.img-ramdisk.gz \
          --cmdline "console=ttyMSM0,115200,n8 root=/dev/mmcblk0p2 rootwait rw init=/sbin/init" \
          --base 0x80000000 \
          --pagesize 2048 \
          --output new-boot.img

    - name: Upload built images
      uses: actions/upload-artifact@v4
      with:
        name: redmi2-built-images
        path: |
          new-boot.img
          immortal-rootfs.sparse.img
          
